---
name: Terraform Lint and Security Scan

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of runner to use for the job.
        default: github-arc-runners
        type: string
      infra-directory:
        description: The directory containing the Terraform code.
        default: infra
        type: string

jobs:
  tf-lint:
    name: Terraform Lint
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.infra-directory }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install Node.js (Dependency Terraform)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform Init
        run:  terraform init -backend=false

      - name: Init TFLint
        run: tflint --init

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Run TFLint
        run: tflint -f compact

  security-scan-tf:
    name: Terraform Security Scan
    runs-on: ${{ inputs.runs-on }}
    needs:
      - tf-lint
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@0.29.0
        with:
          scan-type: "config"
          scan-ref: ${{ inputs.infra-directory }}
          format: "sarif"
          output: "trivy-results.sarif"
          exit-code: "1"
          severity: "CRITICAL,HIGH"
