---
name: Terraform Apply and AWX Resource Creation

on:
  workflow_call:
    inputs:
      runs-on:
        description: The type of runner to use for the job.
        default: github-arc-runners
        type: string
      infra-directory:
        description: The directory containing the Terraform code.
        default: infra
        type: string
      ansible-directory:
        description: The directory containing the Ansible code.
        default: ansible
        type: string
      environment:
        description: The deployment environment (e.g., test, prod).
        default: test
        type: string
      awx-resource-creation-playbook:
        description: The playbook to run for AWX resource creation.
        type: string
        required: true
      awx-deploy-template-name:
        description: The name of the AWX deploy template.
        type: string
        required: true
      ref:
        description: The Git reference (branch, tag, or SHA) to check out.
        default: ""
        type: string
    secrets:
      VAULT_URL:
        description: The URL of the Vault server.
        required: true
      VAULT_TOKEN:
        description: The token for accessing the Vault server.
        required: true

jobs: 
  terraform-apply:
    name: Terraform Apply
    runs-on: ${{ inputs.runs-on }}
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ${{ inputs.infra-directory }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: Install Node.js (Dependency Terraform)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/homelab-pve-ci-agent token-id | PVE_API_TOKEN_ID ;
            kv/data/homelab-pve-ci-agent token-secret | PVE_API_TOKEN_SECRET ;
            kv/data/pdns ci_api_key | PDNS_API_KEY ;
            kv/data/homelab-ansible-sa ssh-key-private | PVE_CI_SSH_PRIVATE_KEY ;
            kv/data/homelab-ansible-sa ssh-key-public | PVE_CI_SSH_PUBLIC_KEY ;
            kv/data/homelab-minio-tf bucket | MINIO_TF_STATE_BUCKET ;
            kv/data/homelab-minio-tf access | MINIO_ACCESS_KEY ;
            kv/data/homelab-minio-tf secret | MINIO_SECRET_KEY ;
            kv/data/homelab-minio-tf endpoint | MINIO_ENDPOINT ;

      - name: Terraform Init
        env:
          AWS_ENDPOINT_URL_S3: ${{ steps.import-secrets.outputs.MINIO_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ steps.import-secrets.outputs.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.import-secrets.outputs.MINIO_SECRET_KEY}}
          AWS_S3_STATE_BUCKET: ${{ steps.import-secrets.outputs.MINIO_TF_STATE_BUCKET }}
          PM_API_TOKEN_ID: ${{ steps.import-secrets.outputs.PVE_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ steps.import-secrets.outputs.PVE_API_TOKEN_SECRET }}
          TF_VAR_pdns_api_key: ${{ steps.import-secrets.outputs.PDNS_API_KEY }}
          TF_VAR_pve_ci_ssh_private_key: ${{ steps.import-secrets.outputs.PVE_CI_SSH_PRIVATE_KEY }}
          TF_VAR_pve_ci_ssh_public_key: ${{ steps.import-secrets.outputs.PVE_CI_SSH_PUBLIC_KEY }}
        run: |
          terraform init -backend-config="bucket=${AWS_S3_STATE_BUCKET}"

      - name: Terraform Apply
        env:
          AWS_ENDPOINT_URL_S3: ${{ steps.import-secrets.outputs.MINIO_ENDPOINT }}
          AWS_ACCESS_KEY_ID: ${{ steps.import-secrets.outputs.MINIO_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.import-secrets.outputs.MINIO_SECRET_KEY}}
          AWS_S3_STATE_BUCKET: ${{ steps.import-secrets.outputs.MINIO_TF_STATE_BUCKET }}
          PM_API_TOKEN_ID: ${{ steps.import-secrets.outputs.PVE_API_TOKEN_ID }}
          PM_API_TOKEN_SECRET: ${{ steps.import-secrets.outputs.PVE_API_TOKEN_SECRET }}
          TF_VAR_pdns_api_key: ${{ steps.import-secrets.outputs.PDNS_API_KEY }}
          TF_VAR_pve_ci_ssh_private_key: ${{ steps.import-secrets.outputs.PVE_CI_SSH_PRIVATE_KEY }}
          TF_VAR_pve_ci_ssh_public_key: ${{ steps.import-secrets.outputs.PVE_CI_SSH_PUBLIC_KEY }}
        run: |
          terraform apply -var-file=envs/${{ inputs.environment }}.tfvars -auto-approve

  create-awx-resources:
    name: Create AWX Resources
    runs-on: ${{ inputs.runs-on }}
    needs:
      - terraform-apply
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Install Ansible Playbook Dependencies
        run: ansible-galaxy collection install awx.awx

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL}}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/awx host | AWX_HOST ;
            kv/data/awx user | AWX_USER ;
            kv/data/awx pw | AWX_PASSWORD ;

      - name: Run AWX Resource Creation Playbook
        env:
          CONTROLLER_HOST: ${{ steps.import-secrets.outputs.AWX_HOST }}
          CONTROLLER_USERNAME: ${{ steps.import-secrets.outputs.AWX_USER}}
          CONTROLLER_PASSWORD: ${{ steps.import-secrets.outputs.AWX_PASSWORD }}
        working-directory: ${{ inputs.ansible-directory }}
        run: |
          ansible-playbook \
            -i localhost \
            -e @envs/${{ inputs.environment }}.yaml \
            ${{ inputs.awx-resource-creation-playbook }}
  
  deploy-app-via-awx:
    name: Deploy App via AWX
    runs-on: ${{ inputs.runs-on }}
    needs:
      - create-awx-resources
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/awx host | AWX_HOST ;
            kv/data/awx user | AWX_USER ;
            kv/data/awx pw | AWX_PASSWORD ;

      - name: Query AWX for Job Template
        id: query_job_template
        env:
          AWX_HOST: ${{ steps.import-secrets.outputs.AWX_HOST }}
          AWX_USER: ${{ steps.import-secrets.outputs.AWX_USER}}
          AWX_PW: ${{ steps.import-secrets.outputs.AWX_PASSWORD }}
          JOB_TEMPLATE_NAME: ${{ inputs.awx-deploy-template-name }}
        run: |
          RESPONSE=$(curl -s -u "$AWX_USER:$AWX_PW" \
            -H "Content-Type: application/json" \
            "https://$AWX_HOST/api/v2/job_templates/?name=${JOB_TEMPLATE_NAME}")

          JOB_TEMPLATE_ID=$(echo "$RESPONSE" | jq -r '.results[0].id')
        
          if [ "$JOB_TEMPLATE_ID" = "null" ] || [ -z "$JOB_TEMPLATE_ID" ]; then
            echo "Error: No job template found with name ${JOB_TEMPLATE_NAME}" >&2
            exit 1
          fi

          echo "Found job template ID: $JOB_TEMPLATE_ID"
          echo "job_template_id=$JOB_TEMPLATE_ID" >> $GITHUB_OUTPUT

      - name: Launch AWX Job Template
        id: launch_job
        env:
          AWX_HOST: ${{ steps.import-secrets.outputs.AWX_HOST }}
          AWX_USER: ${{ steps.import-secrets.outputs.AWX_USER}}
          AWX_PW: ${{ steps.import-secrets.outputs.AWX_PASSWORD }}
        run: |
          JOB_TEMPLATE_ID="${{ steps.query_job_template.outputs.job_template_id }}"
          LAUNCH_RESPONSE=$(curl -L -s -u "$AWX_USER:$AWX_PW" \
            -H "Content-Type: application/json" \
            -X POST \
            -d '{}' \
            "https://$AWX_HOST/api/v2/job_templates/${JOB_TEMPLATE_ID}/launch/")

          JOB_ID=$(echo "$LAUNCH_RESPONSE" | jq -r '.job')
          if [ "$JOB_ID" = "null" ] || [ -z "$JOB_ID" ]; then
            echo "Error: No job ID returned in launch response." >&2
            exit 1
          fi
          echo "Launched Job ID: $JOB_ID"
          echo "job_id=$JOB_ID" >> $GITHUB_OUTPUT

      - name: Poll for Job Status
        env:
          AWX_HOST: ${{ steps.import-secrets.outputs.AWX_HOST }}
          AWX_USER: ${{ steps.import-secrets.outputs.AWX_USER}}
          AWX_PW: ${{ steps.import-secrets.outputs.AWX_PASSWORD }}
        run: |
          JOB_ID="${{ steps.launch_job.outputs.job_id }}"
          echo "Polling AWX for status of Job ID: $JOB_ID"
          STATUS=""
          # Poll every 10 seconds, up to a maximum of 30 minutes (180 iterations)
          for i in {1..180}; do
            RESPONSE=$(curl -s -u "$AWX_USER:$AWX_PW" \
              -H "Content-Type: application/json" \
              "https://$AWX_HOST/api/v2/jobs/$JOB_ID/")

            STATUS=$(echo "$RESPONSE" | jq -r '.status')
            
            if [[ "$STATUS" == "successful" || "$STATUS" == "failed" || "$STATUS" == "error" ]]; then
              break
            fi
            sleep 10
          done

          if [ "$STATUS" != "successful" ]; then
            echo "Job did not complete successfully. Final status: $STATUS"
            exit 1
          else
            echo "Job completed successfully. Final status: $STATUS"
          fi